### ISSUE TITLE
无法恢复购买

### ISSUE THREAD

**Issue by clusflah** [zhangle/ShellBean#10]
**Describe the bug**
早前已经购买终生版，发现功能受限，去恢复购买，显示恢复购买成功，却无法跳转。恢复后，功能依旧受限。

**Screenshots**
![image](https://github.com/user-attachments/assets/79e7b62d-a451-4d29-a8e0-a4b95b219d13)

**iOS (please complete the following information):**
 - Device: iPhone14pro
 - OS: iOS 18.1
 - Version 1.10.8

**Comment by zhangle** [comment]
你好，你可以加我微信 zhangle2006，我看下是什么原因
