### ISSUE TITLE
Server management optimization

### ISSUE THREAD

**Issue by Aoang** [zhangle/ShellBean#3]
## 场景

在管理一定数量的不同用途的服务器时，分组功能不够灵活。且没有备注、标签等功能。

使用习惯上，没有 Royal TSX 实在。Royal TSX 中以 Document 作为项目，Folder 支持多级目录作为细化区分。备注功能一般很少使用，但是一旦需要的时候如果没有，就只能另外找地方记。

服务器界面显示服务器时，除了服务器名称，还显示了用户名和地址。感觉实用性不强。

## 预期

希望分组功能可以是树形的，或者有标签的概念，因为通过多标签过滤可能可以更好的去过滤。

## 目前的操作方式

通过点分的域名格式来处理分组的问题。`runner.poj.us.azure` 作为分组名，服务器名则是 `runner-1.poj`

---

还有一些小问题，不单独开 Issues 了。

- 服务器界面滑动会感觉在掉帧，但是概览界面是没有这个问题的。可能因为开启监控的数量不到十个
- 不知道是否可以新增一个附带家庭组共享的购买选项。通过家庭组区分个人、工作账号时，因为激活方式是 iCloud，不像其他竞品绑定设备，不太友好

**Comment by zhangle** [comment]
感谢建议，服务器管理的功能会逐步加强，增加标签，备注等功能

家人共享的选项已经打开 😀
