### ISSUE TITLE
Ipad上的显示bug

### ISSUE THREAD

**Issue by yinkaaiwu** [zhangle/ShellBean#5]
**Describe the bug**
终端输出的内容会在键盘收起/唤出的时候部分内容会消失

**To Reproduce**
![IMG_0015](https://github.com/user-attachments/assets/18c3107e-605e-4fa2-a524-3af1c3c3e833)
![IMG_0016](https://github.com/user-attachments/assets/5506e89d-9002-45cf-b41e-999d90c3ce06)
![IMG_0017](https://github.com/user-attachments/assets/83a17d40-6c26-4eb2-96e2-1cbe5548d6f5)

https://github.com/user-attachments/assets/65a7c7ac-14c1-4d64-8efc-d026764dbfee

**Expected behavior**
在呼出/收起键盘时，输出内容应该保持不变

**ipadOS (please complete the following information):**
 - Device: [e.g. ipad air-inch m2]
 - OS: [e.g. iOS 17.6.1]
 - Version [e.g. 1.9.11]

**Comment by zhangle** [comment]
收到，稍后版本提供 bug fix

**Comment by yinkaaiwu** [comment]
> 收到，稍后版本提供 bug fix

您好，bug修复了吗？我更新到了最新版，还是有这个问题

**Comment by zhangle** [comment]
你好，新版修复了一个终端显示的bug，但您提到的这个问题没有复现，您能否提供一下操作系统版本和用到的 shell 环境

**Comment by zhangle** [comment]
> > 收到，稍后版本提供 bug fix
> 
> 
> 
> 您好，bug修复了吗？我更新到了最新版，还是有这个问题

你好，新版修复了一个终端显示的bug，但您提到的这个问题没有复现，您能否提供一下操作系统版本和用到的 shell 环境

**Comment by yinkaaiwu** [comment]
> > > 收到，稍后版本提供 bug fix
> > 
> > 
> > 您好，bug修复了吗？我更新到了最新版，还是有这个问题
> 
> 你好，新版修复了一个终端显示的bug，但您提到的这个问题没有复现，您能否提供一下操作系统版本和用到的 shell 环境

使用设备：
ipadOS (please complete the following information):

Device: [e.g. ipad air-inch m2]
OS: [e.g. iOS 17.6.1]
Version [e.g. 1.9.11]

服务器系统
CentOS Linux release 7.4.1708 (Core)

shell环境
zsh 5.0.2 (x86_64-redhat-linux-gnu)

**Comment by zhangle** [comment]
> > > > 收到，稍后版本提供 bug fix
> > > 
> > > 
> > > 您好，bug修复了吗？我更新到了最新版，还是有这个问题
> > 
> > 
> > 你好，新版修复了一个终端显示的bug，但您提到的这个问题没有复现，您能否提供一下操作系统版本和用到的 shell 环境
> 
> 使用设备： ipadOS (please complete the following information):
> 
> Device: [e.g. ipad air-inch m2] OS: [e.g. iOS 17.6.1] Version [e.g. 1.9.11]
> 
> 服务器系统 CentOS Linux release 7.4.1708 (Core)
> 
> shell环境 zsh 5.0.2 (x86_64-redhat-linux-gnu)

请问是在 squeue 这个命令有这种情况，还是终端有内容，就会出现。
我安装了 CentOS 和 ohmyzsh，还未复现这种情况，另外最新版是 1.10.5，你可以升级到最新试试
