### ISSUE TITLE
Add Settings to Hide/Show Monitor and SFTP when connecting to a server

### ISSUE THREAD

**Issue by pathikb** [zhangle/ShellBean#7]
**Is your feature request related to a problem? Please describe.**
When I connect to a server, the monitor and SFTP panels open automatically even though I am not interested in it. I have to manually disable/hide them everytime.

**Describe the solution you'd like**
Give an option in settings if a user wants the SFTP and Monitor to show up automatically every time.

**Comment by zhangle** [comment]
Hi, you can edit the server and deselect these options, save it. Next time you open it it will no longer show SFTP and monitoring.
![WechatIMG1445](https://github.com/user-attachments/assets/e6674119-afba-4d07-b075-6f745926650d)
