### ISSUE TITLE
Option to increase the width of monitor

### ISSUE THREAD

**Issue by pathikb** [zhangle/ShellBean#8]
**Is your feature request related to a problem? Please describe.**
Currently the monitor panel width is too small for any meaningful information to be derived. There is no way to increase the width of the monitor panel

**Describe the solution you'd like**
Allow user to select the width of the monitor vs the terminal area by dragging at the border of the monitor panel.

**Comment by zhangle** [comment]
Hi, adjusting the position of the monitor panel is not very obvious, you can refer to this video.
In the next step, we will optimize the adjustment.


https://github.com/user-attachments/assets/e1a7a32f-2957-4b7a-85d3-c6f16ec1e440
