### ISSUE TITLE
App is constantly Crashing

### ISSUE THREAD

**Issue by olatonrain** [zhangle/ShellBean#9]
**Describe the bug**
After installing about 65 servers app started crashing on my Mac each time I try to open a terminal or add all 65 servers to overview. 

**To Reproduce**
1. Go to 'Overview or Server'
2. Click on 'any server and try to open terminal'

<img width="213" alt="image" src="https://github.com/user-attachments/assets/ab3b3b97-55e7-4bb3-b41d-af0ed90552ae">

**Expected behavior**
I expect the app to be able to function properly without crashing.

**Screenshots**

<img width="213" alt="image" src="https://github.com/user-attachments/assets/6cc6010b-1ab3-4194-8d4d-871face6869d">

**macOS (please complete the following information):**
 - Device: [Macbook pro]
 - OS: [macOS Sequoia]
 - Version [15.1]

**Comment by zhangle** [comment]
Hi, please post the version of the App you are using and the crash log. 
The crash log can be found in the system console.

![WechatIMG1444](https://github.com/user-attachments/assets/0fcdd965-867e-40bc-b13d-944ba59e1cd3)

**Comment by olatonrain** [comment]
It was empty and the issue is still happening.

**Comment by zhangle** [comment]
Hi, When the app crashes, can you copy the crash message from the window
that indicates the crash and send it to me?

olatonrain ***@***.***> 于2024年12月4日周三 12:49写道：

> It was empty and the issue is still happening.
>

**Comment by olatonrain** [comment]
It does not show any message at all it just hang for hours and nothing
works anymore unless I force quit the app.

**Comment by zhangle** [comment]
OK, I get it. Let me figure out how to reproduce the problem.

olatonrain ***@***.***> 于2024年12月4日周三 13:00写道：

> It does not show any message at all it just hang for hours and nothing
> works anymore unless I force quit the app.
>

**Comment by zhangle** [comment]
Hi，Have you upgraded the App to the latest version?

张乐 ***@***.***> 于2024年12月4日周三 13:14写道：

> OK, I get it. Let me figure out how to reproduce the problem.
>
> olatonrain ***@***.***> 于2024年12月4日周三 13:00写道：
>
>> It does not show any message at all it just hang for hours and nothing
>> works anymore unless I force quit the app.
>>

**Comment by olatonrain** [comment]
Anything more than this it will start hanging. Presently if I want to add
another server I have to delete b4 i can add more.

**Comment by zhangle** [comment]
Hi, new version has released at App Store, please update and try it out

**Comment by olatonrain** [comment]
Okay thanks, I will do that now and give you feedback.

**Comment by olatonrain** [comment]
The Mac pc works fine now but on phone once I minimize on iPhone and come
back... It hang and does same thing does on pc. I have to always start all
over again each time I go back to the screen.

**Comment by zhangle** [comment]
ok，I will investigate the issue and provide a new version as soon as
possible.

olatonrain ***@***.***>于2024年12月8日 周日05:36写道：

> The Mac pc works fine now but on phone once I minimize on iPhone and come
> back... It hang and does same thing does on pc. I have to always start all
> over again each time I go back to the screen.
>

**Comment by olatonrain** [comment]
Hi myself and all my students are unable to open the app. It just keept
loading endlessly,

**Comment by zhangle** [comment]
Hello, could you please share some screenshots or a screen recording?

olatonrain ***@***.***> 于2025年1月25日周六 01:39写道：

> Hi myself and all my students are unable to open the app. It just keept
> loading endlessly,
>

**Comment by olatonrain** [comment]
[image: image.png]

**Comment by zhangle** [comment]
Sorry, the images cannot be displayed from issue.

Please resend to my email: ***@***.***


olatonrain ***@***.***> 于2025年1月25日周六 21:37写道：

> [image: image.png]
>

**Comment by olatonrain** [comment]
[image: image.png]this

**Comment by zhangle** [comment]
The images cannot be displayed.

can you post image via github

<img width="200" alt="Image" src="https://github.com/user-attachments/assets/da0821d8-09fc-4a56-b6a5-8bbf920898b6" />

**Comment by olatonrain** [comment]
https://anyimage.io/storage/uploads/2a8c98e745e03925249947caae64eddd

**Comment by zhangle** [comment]
OK,
Did this issue occur after the app upgrade?

olatonrain ***@***.***>于2025年1月25日 周六22:10写道：

> https://anyimage.io/storage/uploads/2a8c98e745e03925249947caae64eddd
>
>

**Comment by olatonrain** [comment]
yes immediately after updating 2 days ago

**Comment by olatonrain** [comment]
When should we be expecting a solution please?

**Comment by zhangle** [comment]
We are debugging this issue and should have results soon!

olatonrain ***@***.***> 于2025年1月26日周日 03:40写道：

> When should we be expecting a solution please?
>

**Comment by zhangle** [comment]
We have released the upgraded version in the App Store, you can try it now.
😀

张乐 ***@***.***> 于2025年1月26日周日 08:13写道：

> We are debugging this issue and should have results soon!
>
> olatonrain ***@***.***> 于2025年1月26日周日 03:40写道：
>
>> When should we be expecting a solution please?
>>

**Comment by olatonrain** [comment]
Oh yes I already did... Thanks for the swift upgrade.
